server:
  port: 8181
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/good_deeds_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000
